---
editor_options:
  chunk_output_type: console
---

# INTERNAL

## Avoid `R CMD check` notes about undefined global objects used in magrittr pipes

cf. <https://github.com/tidyverse/magrittr/issues/29#issuecomment-74313262>

```{r}
utils::globalVariables(names = c("."))
```

## Constants

```{r}
this_pkg <- utils::packageName()
```

# EXPORTED

## `simplify_trace_ids`

NOTES:

-   The underlying issue this function solves is reported upstream in [#2074](https://github.com/plotly/plotly.R/issues/2074). See also [this
    comment](https://github.com/plotly/plotly.R/pull/1365#issuecomment-434063157).

```{r}
#' Make plotly trace identifiers reproducible
#'
#' Replaces the random trace identifiers of a [plotly object][plotly::plot_ly] with simple sequential ones (`trace_1`, `trace_2` etc).
#'
#' This function is especially useful to apply before a plotly object or its JSON representation (as generated for rendered R Markdown / Quarto documents) 
#' is [version controlled](https://en.wikipedia.org/wiki/Version_control) (e.g. via Git).
#' 
#' To also make the htmlwidget identifier reproducible when rendering a Plotly chart, use [htmlwidgets::setWidgetIdSeed()].
#'
#' @param p [Plotly object][plotly::plot_ly] to modify.
#'
#' @return `r pkgsnip::return_label("plotly_obj")`
#' @export
#'
#' @examples
#' p <- plotly::plot_ly(data = mtcars,
#'                      x = ~mpg,
#'                      type = "histogram")
#'
#' p2 <- plotly::plot_ly(data = mtcars,
#'                       x = ~mpg,
#'                       type = "histogram")
#'
#' p_deterministic <- plotlee::simplify_trace_ids(p)
#' p2_deterministic <- plotlee::simplify_trace_ids(p2)
#'
#' names(p$x$visdat)
#' names(p2$x$visdat)
#' names(p_deterministic$x$visdat)
#' names(p2_deterministic$x$visdat)
simplify_trace_ids <- function(p) {
  
  trace_ids <- names(p$x$visdat)
  cur_id <- p$x$cur_data
  
  for (i in seq_along(trace_ids)) {
    
    new_id <- paste0("trace_", i)
    
    p$x %<>% purrr::modify_tree(is_node = is.list,
                                post = \(x) {
                                  
                                  names(x)[names(x) == trace_ids[i]] <- new_id
                                  x
                                })
    
    if (trace_ids[i] == cur_id) {
      p$x$cur_data <- new_id
    }
  }
  
  p
}
```
