# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/plotlee.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#r-markdown-format` for more information on the literate programming approach used applying the R Markdown format.

# plotlee: Unofficial Helper Functions around Plotly
# Copyright (C) 2023 Salim Brüggemann
# 
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

utils::globalVariables(names = c("."))

this_pkg <- utils::packageName()

#' Make plotly data identifier reproducible
#'
#' Replaces the random [data][plotly::plotly_data] identifier of a [plotly object][plotly::plot_ly] with a deterministic hash value of the data's content.
#'
#' This function is especially useful to apply before a plotly object or its JSON representation (as generated for rendered R Markdown / Quarto documents) 
#' is [version controlled](https://en.wikipedia.org/wiki/Version_control) (e.g. via Git).
#' 
#' To also make the htmlwidget identifier reproducible when rendering a Plotly chart, use [htmlwidgets::setWidgetIdSeed()].
#'
#' @param p [Plotly object][plotly::plot_ly] to modify.
#'
#' @return `r pkgsnip::return_label("plotly_obj")`
#' @export
#'
#' @examples
#' p <- plotly::plot_ly(data = mtcars,
#'                      x = ~mpg,
#'                      type = "histogram")
#'
#' p_deterministic <- plotlee::clean_data_hash(p)
#'
#' p$x$cur_data
#' p_deterministic$x$cur_data
clean_data_hash <- function(p) {
  
  id_cur <- checkmate::assert_string(p$x$cur_data,
                                     min.chars = 1L)
  data <- p$x$visdat[[id_cur]]()
  id_new <- rlang::hash(data)
  
  p$x$cur_data <- id_new
  p$x %<>% purrr::modify_tree(is_node = is.list,
                              post = \(x) {
                                
                                names(x)[names(x) == id_cur] <- id_new
                                x
                              })
  p
}
