# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/plotlee.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#r-markdown-format` for more information on the literate programming approach used applying the R Markdown format.

# plotlee: Unofficial Helper Functions around Plotly
# Copyright (C) 2023 Salim Brüggemann
# 
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

utils::globalVariables(names = c("."))

this_pkg <- utils::packageName()

#' Make plotly trace identifiers reproducible
#'
#' Replaces the random trace identifiers of a [plotly object][plotly::plot_ly] with simple sequential ones (`trace_1`, `trace_2` etc).
#'
#' This function is especially useful to apply before a plotly object or its JSON representation (as generated for rendered R Markdown / Quarto documents) 
#' is [version controlled](https://en.wikipedia.org/wiki/Version_control) (e.g. via Git).
#' 
#' To also make the htmlwidget identifier reproducible when rendering a Plotly chart, use [htmlwidgets::setWidgetIdSeed()].
#'
#' @param p [Plotly object][plotly::plot_ly] to modify.
#'
#' @return `r pkgsnip::return_label("plotly_obj")`
#' @export
#'
#' @examples
#' p <- plotly::plot_ly(data = mtcars,
#'                      x = ~mpg,
#'                      type = "histogram")
#'
#' p2 <- plotly::plot_ly(data = mtcars,
#'                       x = ~mpg,
#'                       type = "histogram")
#'
#' p_deterministic <- plotlee::simplify_trace_ids(p)
#' p2_deterministic <- plotlee::simplify_trace_ids(p2)
#'
#' names(p$x$visdat)
#' names(p2$x$visdat)
#' names(p_deterministic$x$visdat)
#' names(p2_deterministic$x$visdat)
simplify_trace_ids <- function(p) {
  
  trace_ids <- names(p$x$visdat)
  cur_id <- p$x$cur_data
  
  for (i in seq_along(trace_ids)) {
    
    new_id <- paste0("trace_", i)
    
    p$x %<>% purrr::modify_tree(is_node = is.list,
                                post = \(x) {
                                  
                                  names(x)[names(x) == trace_ids[i]] <- new_id
                                  x
                                })
    
    if (trace_ids[i] == cur_id) {
      p$x$cur_data <- new_id
    }
  }
  
  p
}
